name: CI
 
on:
  push:
    branches: [ main ]
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v2
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore WVDCUS.sln
 
    - name: Build
      run: msbuild WVDCUS.sln /p:Configuration=Release

    - name: CopyConsole
      uses: canastro/copy-file-action@master
      with:
        source: WVDCUS.Console/bin/Release/
        target: /WVDCUS
        
    - name: CopyService
      uses: canastro/copy-file-action@master
      with:
        source: WVDCUS.Service/bin/Release/
        target: /WVDCUS

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: WVDCUS
        path: |
          WVDCUS/
          !**/*.pdb
          !**/*.xml
