name: CI
 
on:
  push:
    branches: [ main ]
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v2
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore WVDCUS.sln
 
    - name: Build
      run: msbuild WVDCUS.sln /p:Configuration=Release
 
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: WVDCUS
        path: |
          WVDCUS.Console/bin/Release/*/*.dll
          WVDCUS.Console/bin/Release/*/*.config
          WVDCUS.Console/bin/Release/*/*.exe
          WVDCUS.Service/bin/Release/*/*.dll
          WVDCUS.Service/bin/Release/*/*.config
          WVDCUS.Service/bin/Release/*/*.exe
